import { StyleSheet } from 'react-native';

// 创建样式函数，接收主题颜色和暗模式状态
const createStyles = (colors, isDarkMode) => StyleSheet.create({
  container: {
    padding: 12,
    backgroundColor: isDarkMode ? '#121212' : '#F5F5F7',
  },
  section: {
    marginBottom: 15,
    backgroundColor: isDarkMode ? '#1A1A1A' : '#FFFFFF',
    padding: 12,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: isDarkMode ? 0.2 : 0.05,
    shadowRadius: 2,
    elevation: isDarkMode ? 3 : 1,
  },
  label: {
    fontSize: 14,
    marginBottom: 8,
    color: colors.text,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    width: '100%',
  },
  inputLabel: {
    fontSize: 14,
    color: colors.text,
    width: 140,
    marginRight: 8,
  },
  inputRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  input: {
    width: 80,
    height: 40,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255,255,255,0.2)' : '#ddd',
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 14,
    color: colors.text,
    backgroundColor: isDarkMode ? '#2A2A2A' : '#FFFFFF',
    textAlign: 'center',
  },
  numberInput: {
    flex: 1,
    marginHorizontal: 10,
    textAlign: 'center',
  },
  button: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  resultSection: {
    marginTop: 15,
    padding: 12,
    backgroundColor: isDarkMode ? 'rgba(42, 42, 42, 0.9)' : 'rgba(232, 245, 233, 0.9)',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: isDarkMode ? 0.2 : 0.05,
    shadowRadius: 2,
    elevation: 3,
  },
  resultTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 10,
    textAlign: 'center',
  },
  resultItemGroup: {
    marginBottom: 10,
  },
  resultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
    paddingHorizontal: 2,
  },
  resultLabel: {
    fontSize: 14,
    color: colors.text,
    flex: 1,
  },
  resultValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.primary,
    minWidth: 80,
    textAlign: 'right',
  },
  warningContainer: {
    backgroundColor: 'rgba(255, 200, 200, 0.5)',
    padding: 10,
    borderRadius: 8,
    marginTop: 8,
    marginBottom: 12,
  },
  warningText: {
    color: '#d32f2f',
    fontSize: 13,
    lineHeight: 18,
  },
  warningValue: {
    color: '#d32f2f',
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 12,
  },
  recommendButton: {
    backgroundColor: colors?.secondary || '#4caf50',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
  },
  recommendButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  saveSchemeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    padding: 12,
    backgroundColor: isDarkMode ? 'rgba(42, 42, 42, 0.9)' : 'rgba(232, 245, 233, 0.9)',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: isDarkMode ? 0.2 : 0.05,
    shadowRadius: 2,
    elevation: 3,
  },
  schemeNameInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    marginRight: 8,
    fontSize: 14,
    backgroundColor: isDarkMode ? '#2A2A2A' : '#FFFFFF',
    borderColor: isDarkMode ? 'rgba(255,255,255,0.2)' : '#ddd',
  },
  saveButton: {
    paddingHorizontal: 16,
    height: 40,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 80,
    backgroundColor: colors.primary,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    color: colors.text,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 10,
  },
  typeSelector: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 12,
  },
  typeButton: {
    padding: 8,
    marginHorizontal: 5,
    borderRadius: 6,
  },
  typeButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default createStyles; 